[libraries]
jda = "net.dv8tion:JDA:6.2.1"
jspecify = "org.jspecify:jspecify:1.0.0"
slf4j-api = "org.slf4j:slf4j-api:2.0.17"
spotless = "com.diffplug.spotless:spotless-plugin-gradle:8.1.0"
jreleaser = "org.jreleaser:jreleaser-gradle-plugin:1.22.0"

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
